package gotun

import (
	"fmt"
	"gopkg.in/yaml.v3"
	"os"
)

type AppConfig struct {
	WebListen   string `yaml:"web_listen"`   //监听地址
	WebUsername string `yaml:"web_username"` //账号
	WebPassword string `yaml:"web_password"` //密码

	LogLevel    string `yaml:"log_level"`
	EchoListen  string `yaml:"echo_listen"`
	PProfListen string `yaml:"pprof_port"`

	Socks5XServer Socks5XServerConfig `yaml:"socks5x_server"`
}

type Socks5XServerConfig struct {
	ListenPort int `yaml:"listen_port"` //tcp,udp监听端口，仅当TCPListen或UDPListen无值时有效，监听地址为 0.0.0.0:ListenPort
	UDPTimout  int `yaml:"udp_timeout"`
	TCPTimeout int `yaml:"tcp_timeout"`
}

func parseAppConfigFile(fileName string) (*AppConfig, error) {
	data, err := os.ReadFile(fileName)
	if err != nil {
		return nil, err
	}

	var cfg AppConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}

func createAppConfigFile(fileName string) (*AppConfig, error) {
	cfg := AppConfig{
		WebListen:   "0.0.0.0:8080",
		WebUsername: "admin",
		WebPassword: "admin",
		LogLevel:    "info",
		EchoListen:  "0.0.0.0:8081",
		PProfListen: "",
	}

	node := &yaml.Node{
		Kind: yaml.MappingNode,
	}

	err := node.Encode(&cfg)
	if err != nil {
		return nil, err
	}
	addComments(node)
	data, err := yaml.Marshal(node)
	if err != nil {
		return nil, err
	}
	err = os.WriteFile(fileName, data, 0666)
	if err != nil {
		return nil, err
	}
	return &cfg, nil
}

func addComments(node *yaml.Node) {
	for i := 0; i < len(node.Content); i += 2 {
		key := node.Content[i]

		switch key.Value {
		case "web_listen":
			key.HeadComment = "web监听地址"
		case "web_username":
			key.HeadComment = "web登录账号"
		case "web_password":
			key.HeadComment = "web登录密码"
		case "log_level":
			key.HeadComment = "日志等级:debug/info/warn/error"
		case "echo_listen":
			key.HeadComment = "echo服务监听地址,用于测试，客户端向此端口发送什么就回什么，可为空，为空则不启动echo服务"
		case "pprof_port":
			key.HeadComment = "pprof监听地址,可为空"
		case "socks5x_server":
			key.HeadComment = "socks5x服务配置,可为空，为空则不启动socks5x服务"
		}
	}
}

func Welcome(appCfg *AppConfig) {
	str := "\nSTART-------------------------------------\n" +
		"Enjoy your system ^ ^" +
		"\nGenerated by Go-sword" +
		"\nhttps://github.com/sunshinev/go-sword" +
		"\n[Server info]" +
		"\nEcho Listen : " + appCfg.EchoListen +
		"\nPProf Listen : " + appCfg.PProfListen +
		"\n\nStart successful, server is running ...\n" +
		"Please request: " +
		appCfg.WebListen +
		"\nEND-------------------------------------\n"

	fmt.Println(str)
}
