# .github/workflows/release.yaml

name: Publish Go Releases

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: release amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux,windows
        goarch: amd64
        project_path: ./cmd
